title: I am a funky citizen
author: Miruna Lupas
email: miruna.lupas@stud.ubbcluj.ro
description: > # this means to ignore newlines until "baseurl:"
  Hello everyone! This is Miruna, a Computer Science student, active volunteer and funky citizen.
  Here I am trying to talk about my student life, about my projects and about what I do in my free time.

# social links
github_username: funkycitizen24

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
